[2025-04-21T06:52:03.690+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-21T06:52:03.763+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: final_project_BBDL.LandingToBronze manual__2025-04-21T06:52:02.817492+00:00 [queued]>
[2025-04-21T06:52:03.773+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: final_project_BBDL.LandingToBronze manual__2025-04-21T06:52:02.817492+00:00 [queued]>
[2025-04-21T06:52:03.774+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-04-21T06:52:03.822+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): LandingToBronze> on 2025-04-21 06:52:02.817492+00:00
[2025-04-21T06:52:03.827+0000] {standard_task_runner.py:63} INFO - Started process 388 to run task
[2025-04-21T06:52:03.832+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'final_project_BBDL', 'LandingToBronze', 'manual__2025-04-21T06:52:02.817492+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/project_solution.py', '--cfg-path', '/tmp/tmpfw6gn1fv']
[2025-04-21T06:52:03.834+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask LandingToBronze
[2025-04-21T06:52:03.913+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-21T06:52:04.008+0000] {task_command.py:426} INFO - Running <TaskInstance: final_project_BBDL.LandingToBronze manual__2025-04-21T06:52:02.817492+00:00 [running]> on host d8f26088aa24
[2025-04-21T06:52:04.250+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='final_project_BBDL' AIRFLOW_CTX_TASK_ID='LandingToBronze' AIRFLOW_CTX_EXECUTION_DATE='2025-04-21T06:52:02.817492+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-21T06:52:02.817492+00:00'
[2025-04-21T06:52:04.251+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-21T06:52:04.333+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-21T06:52:04.334+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/landing_to_bronze.py", line 21, in main
    spark = SparkSession.builder \
  File "/home/airflow/.local/lib/python3.9/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
  File "/home/airflow/.local/lib/python3.9/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.9/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.9/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/home/airflow/.local/lib/python3.9/site-packages/pyspark/java_gateway.py", line 97, in launch_gateway
    proc = Popen(command, **popen_kwargs)
  File "/usr/local/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/spark/./bin/spark-submit'
[2025-04-21T06:52:04.371+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=final_project_BBDL, task_id=LandingToBronze, run_id=manual__2025-04-21T06:52:02.817492+00:00, execution_date=20250421T065202, start_date=20250421T065203, end_date=20250421T065204
[2025-04-21T06:52:04.416+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task LandingToBronze ([Errno 2] No such file or directory: '/opt/spark/./bin/spark-submit'; 388)
[2025-04-21T06:52:04.443+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-21T06:52:04.497+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-21T06:52:04.530+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
